### ISSUE TITLE
«The 'category.product.addto.wishlist' is not a child of 'catalogsearch.product.addto'»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [frugue/core#35]
`https://frugue.com/uk/catalogsearch/result/?q=bra`

**Comment by dmitry-fedyuk** [comment]
Fixed by [code.dmitry-fedyuk.com/upwork/frugue.com/commit/cb0520af](https://code.dmitry-fedyuk.com/upwork/frugue.com/commit/cb0520af).

**Comment by nadeem0907** [comment]
Hi,
I am looking for the solution, the above link is not working. do you have the solution for that please.
thanks

**Comment by dmitry-fedyuk** [comment]
Yes, I can fix it in your store for **$150**.
You can hire me in Upwork for this task: [upwork.com/fl/mage2pro](https://www.upwork.com/fl/mage2pro)

**Comment by feelcomfort** [comment]
We have the same issue. How can we fix it?
Best regards.

**Comment by dmitry-fedyuk** [comment]
Learn how to read previous messages and do not spam anymore.

**Comment by feelcomfort** [comment]
Hard but truth answer. We never hired an external developer before. Let me discuss it with my collegues and we may ask you for support. Best regards.
