### ISSUE TITLE
«Call to undefined method TemplateMonster\ShopByBrand\Model\ResourceModel\Fulltext\Collection\Interceptor::getMemRequestBuilder()» after the Amasty's «Improved Layered Navigation» module's installation

### ISSUE THREAD

**Issue by dmitry-fedyuk** [frugue/core#40]

**Comment by dmitry-fedyuk** [comment]
Fixed in [2cca0664](https://code.dmitry-fedyuk.com/upwork/frugue.com/commit/2cca0664).

**Comment by SikailoISM** [comment]
Can I get access to fix?

**Comment by dmitry-fedyuk** [comment]
Yes, I can implement the fix in your store for **$150**.
You can hire me in Upwork for it: [upwork.com/fl/mage2pro](https://www.upwork.com/fl/mage2pro)
